/*****************************************************************************\
*    Program:		bgapi2 - Baumer GenTL consumer
*    Purpose:       global definitions of common feature names
*
*    Created:		19.09.2011
*    Author:		Thomas Oelschlaeger
*    Copyright:		Baumer Optronic GmbH, Radeberg
\*****************************************************************************/

#ifndef _BGAPI2_FEATURENAMES_H__
#define _BGAPI2_FEATURENAMES_H__

#define SFNCVERSION 1.5


#define SFNC_DEVICECONTROL "DeviceControl"
#define SFNC_DEVICE_VENDORNAME "DeviceVendorName"
#define SFNC_DEVICE_MODELNAME "DeviceModelName"
#define SFNC_DEVICE_MANUFACTURERINFO "DeviceManufacturerInfo"
#define SFNC_DEVICE_VERSION "DeviceVersion"
#define SFNC_DEVICE_FIRMWAREVERSION "DeviceFirmwareVersion"
#define SFNC_DEVICE_SFNCVERSIONMAJOR "DeviceSFNCVersionMajor"
#define SFNC_DEVICE_SFNCVERSIONMINOR "DeviceSFNCVersionMinor"
#define SFNC_DEVICE_SFNCVERSIONSUBMINOR "DeviceSFNCVersionSubMinor"
#define SFNC_DEVICE_MANIFESTENTRYSELECTOR "DeviceManifestEntrySelector"
#define SFNC_DEVICE_MANIFESTXMLMAJORVERSION "DeviceManifestXMLMajorVersion"
#define SFNC_DEVICE_MANIFESTXMLMINORVERSION "DeviceManifestXMLMinorVersion"
#define SFNC_DEVICE_MANIFESTXMLSUBMINORVERSION "DeviceManifestXMLSubMinorVersion"
#define SFNC_DEVICE_MANIFESTSCHEMAMAJORVERSION "DeviceManifestSchemaMajorVersion"
#define SFNC_DEVICE_MANIFESTSCHEMAMINORVERSION "DeviceManifestSchemaMinorVersion"
#define SFNC_DEVICE_MANIFESTPRIMARYURL "DeviceManifestPrimaryURL"
#define SFNC_DEVICE_MANIFESTSECONDARYURL "DeviceManifestSecondaryURL"
#define SFNC_DEVICE_ID "DeviceID"			 //depreciated SFNC2.0, replaced with "DeviceSerialNumber"
#define SFNC_DEVICE_SERIALNUMBER  "DeviceSerialNumber"  //starting with SFNC2.0 
#define SFNC_DEVICE_USERID "DeviceUserID"
#define SFNC_DEVICE_RESET "DeviceReset"
#define SFNC_DEVICE_REGISTERSSTREAMINGSTART "DeviceRegistersStreamingStart"
#define SFNC_DEVICE_REGISTERSSTREAMINGEND "DeviceRegistersStreamingEnd"
#define SFNC_DEVICE_REGISTERSCHECK "DeviceRegistersCheck"
#define SFNC_DEVICE_REGISTERSVALID "DeviceRegistersValid"
#define SFNC_DEVICE_MAXTHROUGHPUT "DeviceMaxThroughput"
#define SFNC_DEVICE_TEMERATURESELECTOR "DeviceTemperatureSelector"
#define SFNC_DEVICE_TEMPERATURE "DeviceTemperature"
#define SFNC_DEVICE_CLOCKSELECTOR "DeviceClockSelector"
#define SFNC_DEVICE_CLOCKFREQUENCY "DeviceClockFrequency"
#define SFNC_DEVICE_SERIALPORTSELECTOR "DeviceSerialPortSelector"


#define SFNC_IMAGEFORMATCONTROL "ImageFormatControl"
#define SFNC_SENSORWIDTH "SensorWidth"
#define SFNC_SENSORHEIGHT "SensorHeight"
#define SFNC_SENSORTABS "SensorTaps"
#define SFNC_SENSORDIGITIZATIONTABS "SensorDigitizationTaps"
#define SFNC_WIDTHMAX "WidthMax"
#define SFNC_HEIGHTMAX "HeightMax"
#define SFNC_WIDTH "Width"
#define SFNC_HEIGHT "Height"
#define SFNC_OFFSETX "OffsetX"
#define SFNC_OFFSETY "OffsetY"
#define SFNC_LINEPITCH "LinePitch"
#define SFNC_BINNINGHORIZONTAL "BinningHorizontal"
#define SFNC_BINNINGVERTICAL "BinningVertical"
#define SFNC_DECIMATIONHORIZONTAL "DecimationHorizontal"
#define SFNC_DECIMATIONVERTICAL "DecimationVertical"
#define SFNC_REVERSEX "ReverseX"
#define SFNC_REVERSEY "ReverseY"
#define SFNC_PIXELFORMAT "PixelFormat"
#define SFNC_PIXELCODING "PixelCoding"
#define SFNC_PIXELSIZE "PixelSize"
#define SFNC_PIXELCOLORFILTER "PixelColorFilter"
#define SFNC_PIXELDYNAMICRANGEMIN "PixelDynamicRangeMin"
#define SFNC_PIXELDYNAMICRANGEMAX "PixelDynamicRangeMax"
#define SFNC_TESTIMAGESELECTOR "TestImageSelector"


#define SFNC_ACQUISITIONCONTROL "AcquisitionControl"
#define SFNC_ACQUISITION_MODE "AcquisitionMode"
#define SFNC_ACQUISITION_START "AcquisitionStart"
#define SFNC_ACQUISITION_STOP "AcquisitionStop"
#define SFNC_ACQUISITION_ABORT "AcquisitionAbort"
#define SFNC_ACQUISITION_ARM "AcquisitionArm"
#define SFNC_ACQUISITION_FRAMECOUNT "AcquisitionFrameCount"
#define SFNC_ACQUISITION_FRAMERATE "AcquisitionFrameRate"
#define SFNC_ACQUISITION_FRAMERATEABS "AcquisitionFrameRateAbs"
#define SFNC_ACQUISITION_FRAMERATERAW "AcquisitionFrameRateRaw"
#define SFNC_ACQUISITION_LINERATE "AcquisitionLineRate"
#define SFNC_ACQUISITION_LINERATEABS "AcquisitionLineRateAbs"
#define SFNC_ACQUISITION_LINERATERAW "AcquisitionLineRateRaw"
#define SFNC_ACQUISITION_STATUSSELECTOR "AcquisitionStatusSelector"
#define SFNC_ACQUISITION_STATUS "AcquisitionStatus"
#define SFNC_TRIGGERSELECTOR "TriggerSelector"
#define SFNC_TRIGGERMODE "TriggerMode"
#define SFNC_TRIGGERSOFTWARE "TriggerSoftware"
#define SFNC_TRIGGERSOURCE "TriggerSource"
#define SFNC_TRIGGERACTIVATION "TriggerActivation"
#define SFNC_TRIGGEROVERLAP "TriggerOverlap"
#define SFNC_TRIGGERDELAY "TriggerDelay"
#define SFNC_TRIGGERDELAYABS "TriggerDelayAbs"
#define SFNC_TRIGGERDELAYRAW "TriggerDelayRaw"
#define SFNC_TRIGGERDIVIDER "TriggerDivider"
#define SFNC_TRIGGERMULTIPLIER "TriggerMultiplier"
#define SFNC_EXPOSUREMODE "ExposureMode"
#define SFNC_EXPOSURETIME "ExposureTime"
#define SFNC_EXPOSURETIMEABS "ExposureTimeAbs"
#define SFNC_EXPOSURETIMERAW "ExposureTimeRaw"
#define SFNC_EXPOSUREAUTO "ExposureAuto"


#define SFNC_DIGITALIOCONTROL "DigitalIOControl"
#define SFNC_LINESELECTOR "LineSelector"
#define SFNC_LINEMODE "LineMode"
#define SFNC_LINEINVERTER "LineInverter"
#define SFNC_LINESTATUS "LineStatus"
#define SFNC_LINESTATUSALL "LineStatusAll"
#define SFNC_LINESOURCE "LineSource"
#define SFNC_LINEFORMAT "LineFormat"
#define SFNC_USEROUTPUTSELECTOR "UserOutputSelector"
#define SFNC_USEROUTPUTVALUE "UserOutputValue"
#define SFNC_USEROUTPUTVALUEALL "UserOutputValueAll"
#define SFNC_USEROUTPUTVALUEALLMASK "UserOutputValueAllMask"


#define SFNC_COUNTERANDTIMERCONTROL "CounterAndTimerControl"
#define SFNC_COUNTERSELECTOR "CounterSelector"
#define SFNC_COUNTEREVENTSOURCE "CounterEventSource"
#define SFNC_COUNTEREVENTACTIVATION "CounterEventActivation"
#define SFNC_COUNTERRESETSOURCE "CounterResetSource"
#define SFNC_COUNTERRESETACTIVATION "CounterResetActivation"
#define SFNC_COUNTERRESET "CounterReset"
#define SFNC_COUNTERVALUE "CounterValue"
#define SFNC_COUNTERVALUEATRESET "CounterValueAtReset"
#define SFNC_COUNTERDURATION "CounterDuration"
#define SFNC_COUNTERSTATUS "CounterStatus"
#define SFNC_COUNTERTRIGGERSOURCE "CounterTriggerSource"
#define SFNC_COUNTERTRIGGERACTIVATION "CounterTriggerActivation"
#define SFNC_TIMERSELECTOR "TimerSelector"
#define SFNC_TIMERDURATION "TimerDuration"
#define SFNC_TIMERDURATIONABS "TimerDurationAbs"
#define SFNC_TIMERDURATIONRAW "TimerDurationRaw"
#define SFNC_TIMERDELAY "TimerDelay"
#define SFNC_TIMERDELAYABS "TimerDelayAbs"
#define SFNC_TIMERDELAYRAW "TimerDelayRaw"
#define SFNC_TIMERRESET "TimerReset"
#define SFNC_TIMERVALUE "TimerValue"
#define SFNC_TIMERVALUEABS "TimerValueAbs"
#define SFNC_TIMERVALUERAW "TimerValueRaw"
#define SFNC_TIMERSTATUS "TimerStatus"
#define SFNC_TIMERTRIGGERSOURCE "TimerTriggerSource"
#define SFNC_TIMERTRIGGERACTIVATION "TimerTriggerActivation"


#define SFNC_EVENTCONTROL "EventControl"
#define SFNC_EVENTSELECTOR "EventSelector"
#define SFNC_EVENTNOTIFICATION "EventNotification"

#define SFNC_EVENT_FRAMETRIGGERDATA "EventFrameTriggerData"
#define SFNC_EVENT_FRAMETRIGGER "EventFrameTrigger"
#define SFNC_EVENT_FRAMETRIGGERTIMESTAMP "EventFrameTriggerTimestamp"
#define SFNC_EVENT_FRAMETRIGGERFRAMEID "EventFrameTriggerFrameID"

#define SFNC_EVENT_EXPOSUREENDDATA "EventExposureEndData"
#define SFNC_EVENT_EXPOSUREEND "EventExposureEnd"
#define SFNC_EVENT_EXPOSUREENDTIMESTAMP "EventExposureEndTimestamp"
#define SFNC_EVENT_EXPOSUREENDFRAMEID "EventExposureEndFrameID"

#define SFNC_EVENT_ERRORDATA "EventErrorData"
#define SFNC_EVENT_ERROR "EventError"
#define SFNC_EVENT_ERRORTIMESTAMP "EventErrorTimestamp"
#define SFNC_EVENT_ERRORFRAMEID "EventErrorFrameID"
#define SFNC_EVENT_ERRORCODE "EventErrorCode"


#define SFNC_ANALOGCONTROL "AnalogControl"
#define SFNC_GAINSELECTOR "GainSelector"
#define SFNC_GAIN "Gain"
#define SFNC_GAINRAW "GainRaw"
#define SFNC_GAINABS "GainAbs"
#define SFNC_GAINAUTO "GainAuto"
#define SFNC_GAINAUTOBALANCE "GainAutoBalance"
#define SFNC_BLACKLEVELSELECTOR "BlackLevelSelector"
#define SFNC_BLACKLEVEL "BlackLevel"
#define SFNC_BLACKLEVELRAW "BlackLevelRaw"
#define SFNC_BLACKLEVELABS "BlackLevelAbs"
#define SFNC_BLACKLEVELAUTO "BlackLevelAuto"
#define SFNC_BLACKLEVELAUTOBALANCE "BlackLevelAutoBalance"
#define SFNC_WHITECLIPSELECTOR "WhiteClipSelector"
#define SFNC_WHITECLIP "WhiteClip"
#define SFNC_WHITECLIPRAW "WhiteClipRaw"
#define SFNC_WHITECLIPABS "WhiteClipAbs"
#define SFNC_BALANCERATIOSELECTOR "BalanceRatioSelector"
#define SFNC_BALANCERATIO "BalanceRatio"
#define SFNC_BALANCERATIOABS "BalanceRatioAbs"
#define SFNC_BALANCEWHITEAUTO "BalanceWhiteAuto"
#define SFNC_GAMMA "Gamma"


#define SFNC_LUTCONTROL "LUTControl"
#define SFNC_LUTSELECTOR "LUTSelector"
#define SFNC_LUTENABLE "LUTEnable"
#define SFNC_LUTINDEX "LUTIndex"
#define SFNC_LUTVALUE "LUTValue"
#define SFNC_LUTVALUEALL "LUTValueAll"


#define SFNC_ROOT "Root"
#define SFNC_DEVICE "Device"
#define SFNC_TLPARAMSLOCKED "TLParamsLocked"


#define SFNC_TRANSPORTLAYERCONTROL "TransportLayerControl"
#define SFNC_PAYLOADSIZE "PayloadSize"
#define SFNC_GEV_VERSIONMAJOR "GevVersionMajor"
#define SFNC_GEV_VERSIONMINOR "GevVersionMinor"
#define SFNC_GEV_DEVICEMODEISBIGENDIAN "GevDeviceModeIsBigEndian"
#define SFNC_GEV_DEVICECALSS "GevDeviceClass"
#define SFNC_GEV_DEVICEMODECHARACTERSET "GevDeviceModeCharacterSet"
#define SFNC_GEV_INTERFACESELECTOR "GevInterfaceSelector"
#define SFNC_GEV_MACADDRESS "GevMACAddress"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTOR "GevSupportedOptionSelector"
#define SFNC_GEV_SUPPORTEDOPTION "GevSupportedOption"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONLLA "GevSupportedIPConfigurationLLA"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONDHCP "GevSupportedIPConfigurationDHCP"
#define SFNC_GEV_SUPPORTEDIPCONFIGURATIONPERSISTENTIP "GevSupportedIPConfigurationPersistentIP"
#define SFNC_GEV_CURRENTIPCONFIGURATION "GevCurrentIPConfiguration"
#define SFNC_GEV_CURRENTIPCONFIGURATIONLLA "GevCurrentIPConfigurationLLA"
#define SFNC_GEV_CURRENTIPCONFIGURATIONDHCP "GevCurrentIPConfigurationDHCP"
#define SFNC_GEV_CURRENTIPCONFIGURATIONPERSISTENTIP "GevCurrentIPConfigurationPersistentIP"
#define SFNC_GEV_CURRENTIPADDRESS "GevCurrentIPAddress"
#define SFNC_GEV_CURRENTSUBNETMASK "GevCurrentSubnetMask"
#define SFNC_GEV_CURRENTDEFAULTGATEWAY "GevCurrentDefaultGateway"
#define SFNC_GEV_IPCONFIGURATIONSTATUS "GevIPConfigurationStatus"
#define SFNC_GEV_FIRSTURL "GevFirstURL"
#define SFNC_GEV_SECONDURL "GevSecondURL"
#define SFNC_GEV_NUMBEROFINTERFACES "GevNumberOfInterfaces"
#define SFNC_GEV_PERSISTENTIPADDRESS "GevPersistentIPAddress"
#define SFNC_GEV_PERSISTENTSUBNETMASK "GevPersistentSubnetMask"
#define SFNC_GEV_PERSISTENTDEFAULTGATEWAY "GevPersistentDefaultGateway"
#define SFNC_GEV_GEVLINKSPEED "GevLinkSpeed"
#define SFNC_GEV_MESSAGECHANNELCOUNT "GevMessageChannelCount"
#define SFNC_GEV_STREAMCHANNELCOUNT "GevStreamChannelCount"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSUSERDEFINEDNAME "GevSupportedOptionalCommandsUserDefinedName"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSSERIALNUMBER "GevSupportedOptionalCommandsSerialNumber"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSEVENTDATA "GevSupportedOptionalCommandsEVENTDATA"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSEVENT "GevSupportedOptionalCommandsEVENT"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSPACKETRESEND "GevSupportedOptionalCommandsPACKETRESEND"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSWRITEMEM "GevSupportedOptionalCommandsWRITEMEM"
#define SFNC_GEV_SUPPORTEDOPTIONALCOMMANDSCONCATENATION "GevSupportedOptionalCommandsConcatenation"
#define SFNC_GEV_HEARTBEATTIMEOUT "GevHeartbeatTimeout"
#define SFNC_GEV_TIMESTAMPTICKFREQUENCY "GevTimestampTickFrequency"
#define SFNC_GEV_TIMESTAMPCONTROLLATCH "GevTimestampControlLatch"
#define SFNC_GEV_TIMESTAMPCONTROLRESET "GevTimestampControlReset"
#define SFNC_GEV_TIMESTAMPVALUE "GevTimestampValue"
#define SFNC_GEV_DISCOVERYACKDELAY "GevDiscoveryAckDelay"
#define SFNC_GEV_GVCPEXTENDEDSTATUSCODES "GevGVCPExtendedStatusCodes"
#define SFNC_GEV_GVCPPENDINGACK "GevGVCPPendingAck"
#define SFNC_GEV_GVCPHEARTBEATDISABLE "GevGVCPHeartbeatDisable"
#define SFNC_GEV_GVCPPENDINGTIMEOUT "GevGVCPPendingTimeout"
#define SFNC_GEV_PRIMARYAPPLICATIONSWITCHOVERKEY "GevPrimaryApplicationSwitchoverKey"
#define SFNC_GEV_CCP "GevCCP"
#define SFNC_GEV_PRIMARYAPPLICATIONSOCKET "GevPrimaryApplicationSocket"
#define SFNC_GEV_PRIMARYAPPLICATIONIPADDRESS "GevPrimaryApplicationIPAddress"
#define SFNC_GEV_MCPHOSTPORT "GevMCPHostPort"
#define SFNC_GEV_MCDA "GevMCDA"
#define SFNC_GEV_MCTT "GevMCTT"
#define SFNC_GEV_MCRC "GevMCRC"
#define SFNC_GEV_MCSP "GevMCSP"
#define SFNC_GEV_STREAMCHANNELSELECTOR "GevStreamChannelSelector"
#define SFNC_GEV_SCCFGUNCONDITIONALSTREAMING "GevSCCFGUnconditionalStreaming"
#define SFNC_GEV_SCCFGEXTENDEDCHUNKDATA "GevSCCFGExtendedChunkData"
#define SFNC_GEV_SCPDIRECTION "GevSCPDirection"
#define SFNC_GEV_SCPINTERFACEINDEX "GevSCPInterfaceIndex"
#define SFNC_GEV_SCPHOSTPORT "GevSCPHostPort"
#define SFNC_GEV_SCPSFIRETESTPACKET "GevSCPSFireTestPacket"
#define SFNC_GEV_SCPSDONOTFRAGMENT "GevSCPSDoNotFragment"
#define SFNC_GEV_SCPSBIGENDIAN "GevSCPSBigEndian"
#define SFNC_GEV_SCPSPACKETSIZE "GevSCPSPacketSize"
#define SFNC_GEV_SCPD "GevSCPD"
#define SFNC_GEV_SCDA "GevSCDA"
#define SFNC_GEV_SCSP "GevSCSP"
#define SFNC_GEV_MANIFESTENTRYSELECTOR "GevManifestEntrySelector"
#define SFNC_GEV_MANIFESTXMLMAJORVERSION "GevManifestXMLMajorVersion"
#define SFNC_GEV_MANIFESTXMLMINORVERSION "GevManifestXMLMinorVersion"
#define SFNC_GEV_MANIFESTXMLSUBMINORVERSION "GevManifestXMLSubMinorVersion"
#define SFNC_GEV_MANIFESTSCHEMAMAJORVERSION "GevManifestSchemaMajorVersion"
#define SFNC_GEV_MANIFESTSCHEMAMINORVERSION "GevManifestSchemaMinorVersion"
#define SFNC_GEV_MANIFESTPRIMARYURL "GevManifestPrimaryURL"
#define SFNC_GEV_MANIFESTSECONDARYURL "GevManifestSecondaryURL"
#define SFNC_CL_CONFIGURATION "ClConfiguration"
#define SFNC_CL_TIMESLOTSCOUNT "ClTimeSlotsCount"
#define SFNC_DEVICETAPGEOMETRY "DeviceTapGeometry"


#define SFNC_USERSETCONTROL "UserSetControl"
#define SFNC_USERSETSELECTOR "UserSetSelector"
#define SFNC_USERSETLOAD "UserSetLoad"
#define SFNC_USERSETSAVE "UserSetSave"
#define SFNC_USERSETDEFAULTSELECTOR "UserSetDefaultSelector"


#define SFNC_CHUNKDATACONTROL "ChunkDataControl"
#define SFNC_CHUNKMODEACTIVE "ChunkModeActive"
#define SFNC_CHUNKSELECTOR "ChunkSelector"
#define SFNC_CHUNKENABLE "ChunkEnable"
#define SFNC_CHUNKIMAGE "ChunkImage"
#define SFNC_CHUNKOFFSETX "ChunkOffsetX"
#define SFNC_CHUNKOFFSETY "ChunkOffsetY"
#define SFNC_CHUNKWIDTH "ChunkWidth"
#define SFNC_CHUNKHEIGHT "ChunkHeight"
#define SFNC_CHUNKPIXELFORMAT "ChunkPixelFormat"
#define SFNC_CHUNKPIXELDYNAMICRANGEMIN "ChunkPixelDynamicRangeMin"
#define SFNC_CHUNKPIXELDYNAMICRANGEMAX "ChunkPixelDynamicRangeMax"
#define SFNC_CHUNKDYNAMICRANGEMIN "ChunkDynamicRangeMin"
#define SFNC_CHUNKDYNAMICRANGEMAX "ChunkDynamicRangeMax"
#define SFNC_CHUNKTIMESTAMP "ChunkTimestamp"
#define SFNC_CHUNKLINESTATUSALL "ChunkLineStatusAll"
#define SFNC_CHUNKCOUNTERSELECTOR "ChunkCounterSelector"
#define SFNC_CHUNKCOUNTERVALUE "ChunkCounterValue"
#define SFNC_CHUNKCOUNTER "ChunkCounter"
#define SFNC_CHUNKTIMERSELECTOR "ChunkTimerSelector"
#define SFNC_CHUNKTIMERVALUE "ChunkTimerValue"
#define SFNC_CHUNKTIMER "ChunkTimer"
#define SFNC_CHUNKEXPOSURETIME "ChunkExposureTime"
#define SFNC_CHUNKGAINSELECTOR "ChunkGainSelector"
#define SFNC_CHUNKGAIN "ChunkGain"
#define SFNC_CHUNKBLACKLEVELSELECTOR "ChunkBlackLevelSelector"
#define SFNC_CHUNKBLACKLEVEL "ChunkBlackLevel"
#define SFNC_CHUNKLINEPITCH "ChunkLinePitch"
#define SFNC_CHUNKFRAMEID "ChunkFrameID"


#define SFNC_FILEACCESSCONTROL "FileAccessControl"
#define SFNC_FILESELECTOR "FileSelector"
#define SFNC_FILEOPERATIONSELECTOR "FileOperationSelector"
#define SFNC_FILEOPERATIONEXECUTE "FileOperationExecute"
#define SFNC_FILEOPENMODE "FileOpenMode"
#define SFNC_FILEACCESSBUFFER "FileAccessBuffer"
#define SFNC_FILEACCESSOFFSET "FileAccessOffset"
#define SFNC_FILEACCESSLENGTH "FileAccessLength"
#define SFNC_FILEOPERATIONSTATUS "FileOperationStatus"
#define SFNC_FILEOPERATIONRESULT "FileOperationResult"
#define SFNC_FILESIZE "FileSize"


#define SFNC_COLORTRANSFORMATIONCONTROL "ColorTransformationControl"
#define SFNC_COLORTRANSFORMATIONSELECTOR "ColorTransformationSelector"
#define SFNC_COLORTRANSFORMATIONENABLE "ColorTransformationEnable"
#define SFNC_COLORTRANSFORMATIONVALUESELECTOR "ColorTransformationValueSelector"
#define SFNC_COLORTRANSFORMATIONVALUE "ColorTransformationValue"


#define SFNC_ACTIONCONTROL "ActionControl"
#define SFNC_ACTIONDEVICEKEY "ActionDeviceKey"
#define SFNC_ACTIONSELECTOR "ActionSelector"
#define SFNC_ACTIONGROUPMASK "ActionGroupMask"
#define SFNC_ACTIONGROUPKEY "ActionGroupKey"


#define GENTL_SFNC_TLPORT "TLPort"
#define GENTL_SFNC_TLVENDORNAME "TLVendorName"
#define GENTL_SFNC_TLMODELNAME "TLModelName"
#define GENTL_SFNC_TLID "TLID"
#define GENTL_SFNC_TLVERSION "TLVersion"
#define GENTL_SFNC_TLPATH "TLPath"
#define GENTL_SFNC_TLTYPE "TLType"
#define GENTL_SFNC_GENTLVERSIONMAJOR "GenTLVersionMajor"
#define GENTL_SFNC_GENTLVERSIONMINOR "GenTLVersionMinor"
#define GENTL_SFNC_GENTLINTERFACEUPDATELIST "InterfaceUpdateList"
#define GENTL_SFNC_GENTLINTERFACESELECTOR "InterfaceSelector"
#define GENTL_SFNC_GENTLINTERFACEID "InterfaceID"

#define GENTL_SFNC_GEVVERSIONMAJOR "GevVersionMajor"
#define GENTL_SFNC_GEVVERSIONMINOR "GevVersionMinor"
#define GENTL_SFNC_GEVINTERFACEMACADDRESS "GevInterfaceMACAddress"
#define GENTL_SFNC_GEVINTERFACEDEFAULTIPADDRESS "GevInterfaceDefaultIPAddress"
#define GENTL_SFNC_GEVINTERFACEDEFAULTSUBNETMASK "GevInterfaceDefaultSubnetMask"
#define GENTL_SFNC_GEVINTERFACEDEFAULTGATEWAY "GevInterfaceDefaultGateway"


#define GENTL_SFNC_INTERFACEPORT "InterfacePort"
#define GENTL_SFNC_INTERFACEID "InterfaceID"
#define GENTL_SFNC_INTERFACETYPE "InterfaceType"
#define GENTL_SFNC_DEVICEUPDATELIST "DeviceUpdateList"
#define GENTL_SFNC_DEVICESELECTOR "DeviceSelector"
#define GENTL_SFNC_DEVICEID "DeviceID"
#define GENTL_SFNC_DEVICEVENDORNAME "DeviceVendorName"
#define GENTL_SFNC_DEVICEMODELNAME "DeviceModelName"
#define GENTL_SFNC_DEVICEACCESSSTATUS "DeviceAccessStatus"

#define GENTL_SFNC_GEVINTERFACEGATEWAYSELECTOR "GevInterfaceGatewaySelector"
#define GENTL_SFNC_GEVINTERFACEGATEWAY "GevInterfaceGateway"
#define GENTL_SFNC_GEVINTERFACEMACADDRESS "GevInterfaceMACAddress"
#define GENTL_SFNC_GEVINTERFACESUBNETSELECTOR "GevInterfaceSubnetSelector"
#define GENTL_SFNC_GEVINTERFACESUBNETIPADDRESS "GevInterfaceSubnetIPAddress"
#define GENTL_SFNC_GEVINTERFACESUBNETMASK "GevInterfaceSubnetMask"

#define GENTL_SFNC_DEVICEPORT "DevicePort"
#define GENTL_SFNC_DEVICEID "DeviceID"
#define GENTL_SFNC_DEVICEVENDORNAME "DeviceVendorName"
#define GENTL_SFNC_DEVICEMODELNAME "DeviceModelName"
#define GENTL_SFNC_DEVICETYPE "DeviceType"
#define GENTL_SFNC_STREAMSELECTOR "StreamSelector"
#define GENTL_SFNC_STREAMID "StreamID"

#define GENTL_SFNC_GEVDEVICEIPADDRESS "GevDeviceIPAddress"
#define GENTL_SFNC_GEVDEVICESUBNETMASK "GevDeviceSubnetMask"
#define GENTL_SFNC_GEVDEVICEMACADDRESS "GevDeviceMACAddress"
#define GENTL_SFNC_GEVDEVICEGATEWAY "GevDeviceGateway"
#define GENTL_SFNC_DEVICEENDIANESSMECHANISM "DeviceEndianessMechanism"


#define GENTL_SFNC_STREAMPORT "StreamPort"
#define GENTL_SFNC_STREAMID "StreamID"
#define GENTL_SFNC_STREAMANNOUNCEDBUFFERCOUNT "StreamAnnouncedBufferCount"
#define GENTL_SFNC_STREAMACQUISITIONMODESELECTOR "StreamAcquisitionModeSelector"
#define GENTL_SFNC_STREAMANNOUNCEBUFFERMINIMUM "StreamAnnounceBufferMinimum"
#define GENTL_SFNC_STREAMTYPE "StreamType"


#define GENTL_SFNC_BUFFERPORT "BufferPort"
#define GENTL_SFNC_BUFFERDATA "BufferData"
#define GENTL_SFNC_BUFFERUSERDATA "BufferUserData"

// selector values
#define SFNC_CHUNKSELECTORVALUE_IMAGE "ChunkSelector_Image"
#define SFNC_CHUNKSELECTORVALUE_OFFSETX "ChunkSelector_OffsetX"
#define SFNC_CHUNKSELECTORVALUE_OFFSETY "ChunkSelector_OffsetY"
#define SFNC_CHUNKSELECTORVALUE_WIDTH "ChunkSelector_Width"
#define SFNC_CHUNKSELECTORVALUE_HEIGHT "ChunkSelector_Height"
#define SFNC_CHUNKSELECTORVALUE_PIXELFORMAT "ChunkSelector_PixelFormat"
#define SFNC_CHUNKSELECTORVALUE_DYNAMICRANGEMAX "ChunkSelector_DynamicRangeMax"
#define SFNC_CHUNKSELECTORVALUE_DYNAMICRANGEMIN "ChunkSelector_DynamicRangeMin"
#define SFNC_CHUNKSELECTORVALUE_PIXELDYNAMICRANGEMAX "ChunkSelector_PixelDynamicRangeMax"
#define SFNC_CHUNKSELECTORVALUE_PIXELDYNAMICRANGEMIN "ChunkSelector_PixelDynamicRangeMin"
#define SFNC_CHUNKSELECTORVALUE_TIMESTAMP "ChunkSelector_Timestamp"
#define SFNC_CHUNKSELECTORVALUE_LINESTATUSALL "ChunkSelector_LineStatusAll"
#define SFNC_CHUNKSELECTORVALUE_COUNTERVALUE "ChunkSelector_CounterValue"
#define SFNC_CHUNKSELECTORVALUE_TIMERVALUE "ChunkSelector_TimerValue"
#define SFNC_CHUNKSELECTORVALUE_EXPOSURETIME "ChunkSelector_ExposureTime"
#define SFNC_CHUNKSELECTORVALUE_GAIN "ChunkSelector_Gain"
#define SFNC_CHUNKSELECTORVALUE_BLACKLEVEL "ChunkSelector_BlackLevel"
#define SFNC_CHUNKSELECTORVALUE_LINEPITCH "ChunkSelector_LinePitch"
#define SFNC_CHUNKSELECTORVALUE_FRAMEID "ChunkSelector_FrameID"

#define SFNC_DEVICE_TEMERATURESELECTORVALUE_SENSOR "DeviceTemperatureSelector_Sensor"
#define SFNC_DEVICE_TEMERATURESELECTORVALUE_MAINBOARD "DeviceTemperatureSelector_Mainboard"

#define SFNC_DEVICE_CLOCKSELECTORVALUE_SENSOR "DeviceClockSelector_Sensor"
#define SFNC_DEVICE_CLOCKSELECTORVALUE_SENSORDIGITIZATION "DeviceClockSelector_SensorDigitization"
#define SFNC_DEVICE_CLOCKSELECTORVALUE_CAMERALINK "DeviceClockSelector_CameraLink"

#define SFNC_DEVICE_SERIALPORTSELECTORVALUE_CAMERALINK "DeviceSerialPortSelector_CameraLink"

#define SFNC_TESTIMAGESELECTORVALUE_OFF "TestImageSelector_Off"
#define SFNC_TESTIMAGESELECTORVALUE_BLACK "TestImageSelector_Black"
#define SFNC_TESTIMAGESELECTORVALUE_WHITE "TestImageSelector_White"
#define SFNC_TESTIMAGESELECTORVALUE_GREYHORIZONTALRAMP "TestImageSelector_GreyHorizontalRamp"
#define SFNC_TESTIMAGESELECTORVALUE_GREYVERTICALRAMP "TestImageSelector_GreyVerticalRamp"
#define SFNC_TESTIMAGESELECTORVALUE_GREYHORIZONTALRAMPMOVING "TestImageSelector_GreyHorizontalRampMoving"
#define SFNC_TESTIMAGESELECTORVALUE_GREYVERTICALRAMPMOVING "TestImageSelector_GreyVerticalRampMoving"
#define SFNC_TESTIMAGESELECTORVALUE_HORIZONTALLINEMOVING "TestImageSelector_HorzontalLineMoving"
#define SFNC_TESTIMAGESELECTORVALUE_VERTICALLINEMOVING "TestImageSelector_VerticalLineMoving"
#define SFNC_TESTIMAGESELECTORVALUE_COLORBAR "TestImageSelector_ColorBar"
#define SFNC_TESTIMAGESELECTORVALUE_FRAMECOUNTER "TestImageSelector_FrameCounter"

#define SFNC_ACQUISITION_STATUSSELECTORVALUE_ACQUISITIONTRIGGERWAIT "AcquisitionStatusSelector_AcquisitionTriggerWait"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_ACQUISITIONACTIVE "AcquisitionStatusSelector_AcquisitionActive"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_ACQUISITIONTRANSFER "AcquisitionStatusSelector_AcquisitionTransfer"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_FRAMETRIGGERWAIT "AcquisitionStatusSelector_FrameTriggerWait"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_FRAMEACTIVE "AcquisitionStatusSelector_FrameActive"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_FRAMETRANSFER "AcquisitionStatusSelector_FrameTransfer"
#define SFNC_ACQUISITION_STATUSSELECTORVALUE_EXPOSUREACTIVE "AcquisitionStatusSelector_ExposureActive"

#define SFNC_TRIGGERSELECTORVALUE_ACQUISITIONSTART "TriggerSelector_AcquisitionStart"
#define SFNC_TRIGGERSELECTORVALUE_ACQUISITIONEND "TriggerSelector_AcquisitionEnd"
#define SFNC_TRIGGERSELECTORVALUE_ACQUISITIONACTIVE "TriggerSelector_AcquisitionActive"
#define SFNC_TRIGGERSELECTORVALUE_FRAMESTART "TriggerSelector_FrameStart"
#define SFNC_TRIGGERSELECTORVALUE_FRAMEEND "TriggerSelector_FrameEnd"
#define SFNC_TRIGGERSELECTORVALUE_FRAMEACTIVE "TriggerSelector_FrameActive"
#define SFNC_TRIGGERSELECTORVALUE_FRAMEBURSTSTART "TriggerSelector_FrameBurstStart"
#define SFNC_TRIGGERSELECTORVALUE_FRAMEBURSTEND "TriggerSelector_FrameBurstEnd"
#define SFNC_TRIGGERSELECTORVALUE_FRAMEBURSTACTIVE "TriggerSelector_FrameBurstActive"
#define SFNC_TRIGGERSELECTORVALUE_LINESTART "TriggerSelector_LineStart"
#define SFNC_TRIGGERSELECTORVALUE_EXPOSURESTART "TriggerSelector_ExposureStart"
#define SFNC_TRIGGERSELECTORVALUE_EXPOSUREEND "TriggerSelector_ExposureEnd"
#define SFNC_TRIGGERSELECTORVALUE_EXPOSUREACTIVE "TriggerSelector_ExposureActive"
            
#define SFNC_LINESELECTORVALUE_LINE0 "LineSelector_Line0"
#define SFNC_LINESELECTORVALUE_LINE1 "LineSelector_Line1"
#define SFNC_LINESELECTORVALUE_LINE2 "LineSelector_Line2"
#define SFNC_LINESELECTORVALUE_LINE3 "LineSelector_Line3"
#define SFNC_LINESELECTORVALUE_LINE4 "LineSelector_Line4"
#define SFNC_LINESELECTORVALUE_LINE5 "LineSelector_Line5"
#define SFNC_LINESELECTORVALUE_LINE6 "LineSelector_Line6"
#define SFNC_LINESELECTORVALUE_LINE7 "LineSelector_Line7"
#define SFNC_LINESELECTORVALUE_CC1 "LineSelector_CC1"
#define SFNC_LINESELECTORVALUE_CC2 "LineSelector_CC2"
#define SFNC_LINESELECTORVALUE_CC3 "LineSelector_CC3"
#define SFNC_LINESELECTORVALUE_CC4 "LineSelector_CC4"

#define SFNC_USEROUTPUTSELECTORVALUE_USEROUTPUT0 "UserOutputSelector_UserOutput0"
#define SFNC_USEROUTPUTSELECTORVALUE_USEROUTPUT1 "UserOutputSelector_UserOutput1"
#define SFNC_USEROUTPUTSELECTORVALUE_USEROUTPUT2 "UserOutputSelector_UserOutput2"
#define SFNC_USEROUTPUTSELECTORVALUE_USEROUTPUT3 "UserOutputSelector_UserOutput3"

#define SFNC_COUNTERSELECTORVALUE_COUNTER1 "CounterSelector_Counter1"
#define SFNC_COUNTERSELECTORVALUE_COUNTER2 "CounterSelector_Counter2"
#define SFNC_COUNTERSELECTORVALUE_COUNTER3 "CounterSelector_Counter3"
#define SFNC_COUNTERSELECTORVALUE_COUNTER4 "CounterSelector_Counter4"
#define SFNC_COUNTERSELECTORVALUE_COUNTER5 "CounterSelector_Counter5"
#define SFNC_COUNTERSELECTORVALUE_COUNTER6 "CounterSelector_Counter6"
#define SFNC_COUNTERSELECTORVALUE_COUNTER7 "CounterSelector_Counter7"
#define SFNC_COUNTERSELECTORVALUE_COUNTER8 "CounterSelector_Counter8"

#define SFNC_TIMERSELECTORVALUE_TIMER1 "TimerSelector_Timer1"
#define SFNC_TIMERSELECTORVALUE_TIMER2 "TimerSelector_Timer2"
#define SFNC_TIMERSELECTORVALUE_TIMER3 "TimerSelector_Timer3"
#define SFNC_TIMERSELECTORVALUE_TIMER4 "TimerSelector_Timer4"
#define SFNC_TIMERSELECTORVALUE_TIMER5 "TimerSelector_Timer5"
#define SFNC_TIMERSELECTORVALUE_TIMER6 "TimerSelector_Timer6"
#define SFNC_TIMERSELECTORVALUE_TIMER7 "TimerSelector_Timer7"
#define SFNC_TIMERSELECTORVALUE_TIMER8 "TimerSelector_Timer8"

#define SFNC_EVENTSELECTORVALUE_ACQUISITIONTRIGGER "EventSelector_AcquisitionTrigger"
#define SFNC_EVENTSELECTORVALUE_ACQUISITIONSTART "EventSelector_AcquisitionStart"
#define SFNC_EVENTSELECTORVALUE_ACQUISITIONEND "EventSelector_AcquisitionEnd"
#define SFNC_EVENTSELECTORVALUE_ACQUISITIONTRANSFERSTART "EventSelector_AcquisitionTransferStart"
#define SFNC_EVENTSELECTORVALUE_ACQUISITIONTRANSFEREND "EventSelector_AcquisitionTransferEnd"
#define SFNC_EVENTSELECTORVALUE_ACQUISITIONERROR "EventSelector_AcquisitionError"
#define SFNC_EVENTSELECTORVALUE_FRAMETRIGGER "EventSelector_FrameTrigger"
#define SFNC_EVENTSELECTORVALUE_FRAMESTART "EventSelector_FrameStart"
#define SFNC_EVENTSELECTORVALUE_FRAMEEND "EventSelector_FrameEnd"
#define SFNC_EVENTSELECTORVALUE_FRAMEBURSTSTART "EventSelector_FrameBurstStart"
#define SFNC_EVENTSELECTORVALUE_FRAMEBURSTEND "EventSelector_FrameBurstEnd"
#define SFNC_EVENTSELECTORVALUE_FRAMETRANSFERSTART "EventSelector_FrameTransferStart"
#define SFNC_EVENTSELECTORVALUE_FRAMETRANSFEREND "EventSelector_FrameTransferEnd"
#define SFNC_EVENTSELECTORVALUE_EXPOSURESTART "EventSelector_ExposureStart"
#define SFNC_EVENTSELECTORVALUE_EXPOSUREEND "EventSelector_ExposureEnd"
#define SFNC_EVENTSELECTORVALUE_COUNTER1START "EventSelector_Counter1Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER2START "EventSelector_Counter2Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER3START "EventSelector_Counter3Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER4START "EventSelector_Counter4Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER5START "EventSelector_Counter5Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER6START "EventSelector_Counter6Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER7START "EventSelector_Counter7Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER8START "EventSelector_Counter8Start"
#define SFNC_EVENTSELECTORVALUE_COUNTER1END "EventSelector_Counter1End"
#define SFNC_EVENTSELECTORVALUE_COUNTER2END "EventSelector_Counter2End"
#define SFNC_EVENTSELECTORVALUE_COUNTER3END "EventSelector_Counter3End"
#define SFNC_EVENTSELECTORVALUE_COUNTER4END "EventSelector_Counter4End"
#define SFNC_EVENTSELECTORVALUE_COUNTER5END "EventSelector_Counter5End"
#define SFNC_EVENTSELECTORVALUE_COUNTER6END "EventSelector_Counter6End"
#define SFNC_EVENTSELECTORVALUE_COUNTER7END "EventSelector_Counter7End"
#define SFNC_EVENTSELECTORVALUE_COUNTER8END "EventSelector_Counter8End"
#define SFNC_EVENTSELECTORVALUE_TIMER1START "EventSelector_Timer1Start"
#define SFNC_EVENTSELECTORVALUE_TIMER2START "EventSelector_Timer2Start"
#define SFNC_EVENTSELECTORVALUE_TIMER3START "EventSelector_Timer3Start"
#define SFNC_EVENTSELECTORVALUE_TIMER4START "EventSelector_Timer4Start"
#define SFNC_EVENTSELECTORVALUE_TIMER5START "EventSelector_Timer5Start"
#define SFNC_EVENTSELECTORVALUE_TIMER6START "EventSelector_Timer6Start"
#define SFNC_EVENTSELECTORVALUE_TIMER7START "EventSelector_Timer7Start"
#define SFNC_EVENTSELECTORVALUE_TIMER8START "EventSelector_Timer8Start"
#define SFNC_EVENTSELECTORVALUE_TIMER1END "EventSelector_Timer1End"
#define SFNC_EVENTSELECTORVALUE_TIMER2END "EventSelector_Timer2End"
#define SFNC_EVENTSELECTORVALUE_TIMER3END "EventSelector_Timer3End"
#define SFNC_EVENTSELECTORVALUE_TIMER4END "EventSelector_Timer4End"
#define SFNC_EVENTSELECTORVALUE_TIMER5END "EventSelector_Timer5End"
#define SFNC_EVENTSELECTORVALUE_TIMER6END "EventSelector_Timer6End"
#define SFNC_EVENTSELECTORVALUE_TIMER7END "EventSelector_Timer7End"
#define SFNC_EVENTSELECTORVALUE_TIMER8END "EventSelector_Timer8End"
#define SFNC_EVENTSELECTORVALUE_LINE0RISINGEDGE "EventSelector_Line0RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE1RISINGEDGE "EventSelector_Line1RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE2RISINGEDGE "EventSelector_Line2RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE3RISINGEDGE "EventSelector_Line3RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE4RISINGEDGE "EventSelector_Line4RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE5RISINGEDGE "EventSelector_Line5RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE6RISINGEDGE "EventSelector_Line6RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE7RISINGEDGE "EventSelector_Line7RisingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE0FALLINGEDGE "EventSelector_Line0FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE1FALLINGEDGE "EventSelector_Line1FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE2FALLINGEDGE "EventSelector_Line2FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE3FALLINGEDGE "EventSelector_Line3FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE4FALLINGEDGE "EventSelector_Line4FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE5FALLINGEDGE "EventSelector_Line5FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE6FALLINGEDGE "EventSelector_Line6FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE7FALLINGEDGE "EventSelector_Line7FallingEdge"
#define SFNC_EVENTSELECTORVALUE_LINE0ANYEDGE "EventSelector_Line0AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE1ANYEDGE "EventSelector_Line1AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE2ANYEDGE "EventSelector_Line2AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE3ANYEDGE "EventSelector_Line3AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE4ANYEDGE "EventSelector_Line4AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE5ANYEDGE "EventSelector_Line5AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE6ANYEDGE "EventSelector_Line6AnyEdge"
#define SFNC_EVENTSELECTORVALUE_LINE7ANYEDGE "EventSelector_Line7AnyEdge"
#define SFNC_EVENTSELECTORVALUE_ERROR "EventSelector_Error"
#define SFNC_EVENTSELECTORVALUE_ERRORS "EventSelector_Errors"

#define SFNC_GAINSELECTORVALUE_ALL "GainSelector_All"
#define SFNC_GAINSELECTORVALUE_RED "GainSelector_Red"
#define SFNC_GAINSELECTORVALUE_GREEN "GainSelector_Green"
#define SFNC_GAINSELECTORVALUE_BLUE "GainSelector_Blue"
#define SFNC_GAINSELECTORVALUE_Y "GainSelector_Y"
#define SFNC_GAINSELECTORVALUE_U "GainSelector_U"
#define SFNC_GAINSELECTORVALUE_V "GainSelector_V"
#define SFNC_GAINSELECTORVALUE_TAP1 "GainSelector_Tap1"
#define SFNC_GAINSELECTORVALUE_TAP2 "GainSelector_Tap2"
#define SFNC_GAINSELECTORVALUE_TAP3 "GainSelector_Tap3"
#define SFNC_GAINSELECTORVALUE_TAP4 "GainSelector_Tap4"
#define SFNC_GAINSELECTORVALUE_TAP5 "GainSelector_Tap5"
#define SFNC_GAINSELECTORVALUE_TAP6 "GainSelector_Tap6"
#define SFNC_GAINSELECTORVALUE_TAP7 "GainSelector_Tap7"
#define SFNC_GAINSELECTORVALUE_TAP8 "GainSelector_Tap8"
#define SFNC_GAINSELECTORVALUE_ANALOGALL "GainSelector_AnalogAll"
#define SFNC_GAINSELECTORVALUE_ANALOGRED "GainSelector_AnalogRed"
#define SFNC_GAINSELECTORVALUE_ANALOGGREEN "GainSelector_AnalogGreen"
#define SFNC_GAINSELECTORVALUE_ANALOGBLUE "GainSelector_AnalogBlue"
#define SFNC_GAINSELECTORVALUE_ANALOGY "GainSelector_AnalogY"
#define SFNC_GAINSELECTORVALUE_ANALOGU "GainSelector_AnalogU"
#define SFNC_GAINSELECTORVALUE_ANALOGV "GainSelector_AnalogV"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP1 "GainSelector_AnalogTap1"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP2 "GainSelector_AnalogTap2"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP3 "GainSelector_AnalogTap3"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP4 "GainSelector_AnalogTap4"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP5 "GainSelector_AnalogTap5"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP6 "GainSelector_AnalogTap6"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP7 "GainSelector_AnalogTap7"
#define SFNC_GAINSELECTORVALUE_ANALOGTAP8 "GainSelector_AnalogTap8"
#define SFNC_GAINSELECTORVALUE_DIGITALALL "GainSelector_DigitalAll"
#define SFNC_GAINSELECTORVALUE_DIGITALRED "GainSelector_DigitalRed"
#define SFNC_GAINSELECTORVALUE_DIGITALGREEN "GainSelector_DigitalGreen"
#define SFNC_GAINSELECTORVALUE_DIGITALBLUE "GainSelector_DigitalBlue"
#define SFNC_GAINSELECTORVALUE_DIGITALY "GainSelector_DigitalY"
#define SFNC_GAINSELECTORVALUE_DIGITALU "GainSelector_DigitalU"
#define SFNC_GAINSELECTORVALUE_DIGITALV "GainSelector_DigitalV"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP1 "GainSelector_DigitalTap1"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP2 "GainSelector_DigitalTap2"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP3 "GainSelector_DigitalTap3"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP4 "GainSelector_DigitalTap4"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP5 "GainSelector_DigitalTap5"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP6 "GainSelector_DigitalTap6"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP7 "GainSelector_DigitalTap7"
#define SFNC_GAINSELECTORVALUE_DIGITALTAP8 "GainSelector_DigitalTap8"

#define SFNC_BLACKLEVELSELECTORVALUE_ALL "BlackLevelSelector_All"
#define SFNC_BLACKLEVELSELECTORVALUE_RED "BlackLevelSelector_Red"
#define SFNC_BLACKLEVELSELECTORVALUE_GREEN "BlackLevelSelector_Green"
#define SFNC_BLACKLEVELSELECTORVALUE_BLUE "BlackLevelSelector_Blue"
#define SFNC_BLACKLEVELSELECTORVALUE_Y "BlackLevelSelector_Y"
#define SFNC_BLACKLEVELSELECTORVALUE_U "BlackLevelSelector_U"
#define SFNC_BLACKLEVELSELECTORVALUE_V "BlackLevelSelector_V"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP1 "BlackLevelSelector_Tap1"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP2 "BlackLevelSelector_Tap2"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP3 "BlackLevelSelector_Tap3"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP4 "BlackLevelSelector_Tap4"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP5 "BlackLevelSelector_Tap5"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP6 "BlackLevelSelector_Tap6"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP7 "BlackLevelSelector_Tap7"
#define SFNC_BLACKLEVELSELECTORVALUE_TAP8 "BlackLevelSelector_Tap8"

#define SFNC_WHITECLIPSELECTORVALUE_ALL "WhiteClipSelector_All"
#define SFNC_WHITECLIPSELECTORVALUE_RED "WhiteClipSelector_Red"
#define SFNC_WHITECLIPSELECTORVALUE_GREEN "WhiteClipSelector_Green"
#define SFNC_WHITECLIPSELECTORVALUE_BLUE "WhiteClipSelector_Blue"
#define SFNC_WHITECLIPSELECTORVALUE_Y "WhiteClipSelector_Y"
#define SFNC_WHITECLIPSELECTORVALUE_U "WhiteClipSelector_U"
#define SFNC_WHITECLIPSELECTORVALUE_V "WhiteClipSelector_V"
#define SFNC_WHITECLIPSELECTORVALUE_TAP1 "WhiteClipSelector_Tap1"
#define SFNC_WHITECLIPSELECTORVALUE_TAP2 "WhiteClipSelector_Tap2"
#define SFNC_WHITECLIPSELECTORVALUE_TAP3 "WhiteClipSelector_Tap3"
#define SFNC_WHITECLIPSELECTORVALUE_TAP4 "WhiteClipSelector_Tap4"
#define SFNC_WHITECLIPSELECTORVALUE_TAP5 "WhiteClipSelector_Tap5"
#define SFNC_WHITECLIPSELECTORVALUE_TAP6 "WhiteClipSelector_Tap6"
#define SFNC_WHITECLIPSELECTORVALUE_TAP7 "WhiteClipSelector_Tap7"
#define SFNC_WHITECLIPSELECTORVALUE_TAP8 "WhiteClipSelector_Tap8"

#define SFNC_BALANCERATIOSELECTORVALUE_ALL "BalanceRatioSelector_All"
#define SFNC_BALANCERATIOSELECTORVALUE_RED "BalanceRatioSelector_Red"
#define SFNC_BALANCERATIOSELECTORVALUE_GREEN "BalanceRatioSelector_Green"
#define SFNC_BALANCERATIOSELECTORVALUE_BLUE "BalanceRatioSelector_Blue"
#define SFNC_BALANCERATIOSELECTORVALUE_Y "BalanceRatioSelector_Y"
#define SFNC_BALANCERATIOSELECTORVALUE_U "BalanceRatioSelector_U"
#define SFNC_BALANCERATIOSELECTORVALUE_V "BalanceRatioSelector_V"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP1 "BalanceRatioSelector_Tap1"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP2 "BalanceRatioSelector_Tap2"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP3 "BalanceRatioSelector_Tap3"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP4 "BalanceRatioSelector_Tap4"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP5 "BalanceRatioSelector_Tap5"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP6 "BalanceRatioSelector_Tap6"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP7 "BalanceRatioSelector_Tap7"
#define SFNC_BALANCERATIOSELECTORVALUE_TAP8 "BalanceRatioSelector_Tap8"

#define SFNC_LUTSELECTORVALUE_LUMINANCE "LUTSelector_Luminance"
#define SFNC_LUTSELECTORVALUE_RED "LUTSelector_Red"
#define SFNC_LUTSELECTORVALUE_GREEN "LUTSelector_Green"
#define SFNC_LUTSELECTORVALUE_BLUE "LUTSelector_Blue"
   
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_IPCONFIGURATIONLLA "GevSupportedOptionSelector_IPConfigurationLLA"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_IPCONFIGURATIONDHCP "GevSupportedOptionSelector_IPConfigurationDHCP"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_IPCONFIGURATIONPERSISTENTIP "GevSupportedOptionSelector_IPConfigurationPersistentIP"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNELSOURCESOCKET "GevSupportedOptionSelector_StreamChannelSourceSocket"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_MESSAGECHANNELSOURCESOCKET "GevSupportedOptionSelector_MessageChannelSourceSocket"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_COMMANDSCONCATENATION "GevSupportedOptionSelector_CommandsConcatenation"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_WRITEMEM "GevSupportedOptionSelector_WriteMem"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_PACKETRESEND "GevSupportedOptionSelector_PacketResend"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_EVENT "GevSupportedOptionSelector_Event"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_EVENTDATA "GevSupportedOptionSelector_EventData"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_PENDINGACK "GevSupportedOptionSelector_PendingAck"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_ACTION "GevSupportedOptionSelector_Action"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_PRIMARYAPPLICATIONSWITCHOVER "GevSupportedOptionSelector_PrimaryApplicationSwitchover"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_EXTENDEDSTATUSCODES "GevSupportedOptionSelector_ExtendedStatusCodes"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_DISCOVERYACKDELAY "GevSupportedOptionSelector_DiscoveryAckDelay"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_DISCOVERYACKDELAYWRITABLE "GevSupportedOptionSelector_DiscoveryAckDelayWritable"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_TESTDATA "GevSupportedOptionSelector_TestData"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_MANIFESTTABLE "GevSupportedOptionSelector_ManifestTable"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_CCPAPPLICATIONSOCKET "GevSupportedOptionSelector_CCPApplicationSocket"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_LINKSPEED "GevSupportedOptionSelector_LinkSpeed"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_HEARTBEATDISABLE "GevSupportedOptionSelector_HeartbeatDisable"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_SERIALNUMBER "GevSupportedOptionSelector_SerialNumber"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_USERDEFINEDNAME "GevSupportedOptionSelector_UserDefinedName"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL0BIGANDLITTLEENDIAN "GevSupportedOptionSelector_StreamChannel0BigAndLittleEndian"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL0IPREASSEMBLY "GevSupportedOptionSelector_StreamChannel0IPReassembly"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL0UNCONDITIONALSTREAMING "GevSupportedOptionSelector_StreamChannel0UnconditionalStreaming"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL0EXTENDEDCHUNKDATA "GevSupportedOptionSelector_StreamChannel0ExtendedChunkData"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL1BIGANDLITTLEENDIAN "GevSupportedOptionSelector_StreamChannel1BigAndLittleEndian"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL1IPREASSEMBLY "GevSupportedOptionSelector_StreamChannel1IPReassembly"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL1UNCONDITIONALSTREAMING "GevSupportedOptionSelector_StreamChannel1UnconditionalStreaming"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL1EXTENDEDCHUNKDATA "GevSupportedOptionSelector_StreamChannel1ExtendedChunkData"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL2BIGANDLITTLEENDIAN "GevSupportedOptionSelector_StreamChannel2BigAndLittleEndian"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL2IPREASSEMBLY "GevSupportedOptionSelector_StreamChannel2IPReassembly"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL2UNCONDITIONALSTREAMING "GevSupportedOptionSelector_StreamChannel2UnconditionalStreaming"
#define SFNC_GEV_SUPPORTEDOPTIONSELECTORVALUE_STREAMCHANNEL2EXTENDEDCHUNKDATA "GevSupportedOptionSelector_StreamChannel2ExtendedChunkData"

#define SFNC_USERSETSELECTORVALUE_DEFAULT "UserSetSelector_Default"
#define SFNC_USERSETSELECTORVALUE_USERSET1 "UserSetSelector_UserSet1"
#define SFNC_USERSETSELECTORVALUE_USERSET2 "UserSetSelector_UserSet2"
#define SFNC_USERSETSELECTORVALUE_USERSET3 "UserSetSelector_UserSet3"
#define SFNC_USERSETSELECTORVALUE_USERSET4 "UserSetSelector_UserSet4"

#define SFNC_USERSETDEFAULTSELECTORVALUE_DEFAULT "UserSetDefaultSelector_Default"
#define SFNC_USERSETDEFAULTSELECTORVALUE_USERSET1 "UserSetDefaultSelector_UserSet1"
#define SFNC_USERSETDEFAULTSELECTORVALUE_USERSET2 "UserSetDefaultSelector_UserSet2"
#define SFNC_USERSETDEFAULTSELECTORVALUE_USERSET3 "UserSetDefaultSelector_UserSet3"
#define SFNC_USERSETDEFAULTSELECTORVALUE_USERSET4 "UserSetDefaultSelector_UserSet4"

#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER1 "ChunkCounterSelector_Counter1"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER2 "ChunkCounterSelector_Counter2"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER3 "ChunkCounterSelector_Counter3"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER4 "ChunkCounterSelector_Counter4"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER5 "ChunkCounterSelector_Counter5"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER6 "ChunkCounterSelector_Counter6"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER7 "ChunkCounterSelector_Counter7"
#define SFNC_CHUNKCOUNTERSELECTORVALUE_COUNTER8 "ChunkCounterSelector_Counter8"

#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER1 "ChunkTimerSelector_Timer1"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER2 "ChunkTimerSelector_Timer2"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER3 "ChunkTimerSelector_Timer3"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER4 "ChunkTimerSelector_Timer4"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER5 "ChunkTimerSelector_Timer5"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER6 "ChunkTimerSelector_Timer6"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER7 "ChunkTimerSelector_Timer7"
#define SFNC_CHUNKTIMERSELECTORVALUE_TIMER8 "ChunkTimerSelector_Timer8"

#define SFNC_CHUNKGAINSELECTORVALUE_ALL "ChunkGainSelector_All"
#define SFNC_CHUNKGAINSELECTORVALUE_RED "ChunkGainSelector_Red"
#define SFNC_CHUNKGAINSELECTORVALUE_GREEN "ChunkGainSelector_Green"
#define SFNC_CHUNKGAINSELECTORVALUE_BLUE "ChunkGainSelector_Blue"
#define SFNC_CHUNKGAINSELECTORVALUE_Y "ChunkGainSelector_Y"
#define SFNC_CHUNKGAINSELECTORVALUE_U "ChunkGainSelector_U"
#define SFNC_CHUNKGAINSELECTORVALUE_V "ChunkGainSelector_V"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP1 "ChunkGainSelector_Tap1"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP2 "ChunkGainSelector_Tap2"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP3 "ChunkGainSelector_Tap3"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP4 "ChunkGainSelector_Tap4"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP5 "ChunkGainSelector_Tap5"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP6 "ChunkGainSelector_Tap6"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP7 "ChunkGainSelector_Tap7"
#define SFNC_CHUNKGAINSELECTORVALUE_TAP8 "ChunkGainSelector_Tap8"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGALL "ChunkGainSelector_AnalogAll"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGRED "ChunkGainSelector_AnalogRed"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGGREEN "ChunkGainSelector_AnalogGreen"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGBLUE "ChunkGainSelector_AnalogBlue"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGY "ChunkGainSelector_AnalogY"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGU "ChunkGainSelector_AnalogU"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGV "ChunkGainSelector_AnalogV"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP1 "ChunkGainSelector_AnalogTap1"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP2 "ChunkGainSelector_AnalogTap2"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP3 "ChunkGainSelector_AnalogTap3"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP4 "ChunkGainSelector_AnalogTap4"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP5 "ChunkGainSelector_AnalogTap5"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP6 "ChunkGainSelector_AnalogTap6"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP7 "ChunkGainSelector_AnalogTap7"
#define SFNC_CHUNKGAINSELECTORVALUE_ANALOGTAP8 "ChunkGainSelector_AnalogTap8"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALALL "ChunkGainSelector_DigitalAll"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALRED "ChunkGainSelector_DigitalRed"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALGREEN "ChunkGainSelector_DigitalGreen"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALBLUE "ChunkGainSelector_DigitalBlue"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALY "ChunkGainSelector_DigitalY"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALU "ChunkGainSelector_DigitalU"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALV "ChunkGainSelector_DigitalV"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP1 "ChunkGainSelector_DigitalTap1"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP2 "ChunkGainSelector_DigitalTap2"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP3 "ChunkGainSelector_DigitalTap3"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP4 "ChunkGainSelector_DigitalTap4"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP5 "ChunkGainSelector_DigitalTap5"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP6 "ChunkGainSelector_DigitalTap6"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP7 "ChunkGainSelector_DigitalTap7"
#define SFNC_CHUNKGAINSELECTORVALUE_DIGITALTAP8 "ChunkGainSelector_DigitalTap8"

#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_ALL "ChunkBlackLevelSelector_All"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_RED "ChunkBlackLevelSelector_Red"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_GREEN "ChunkBlackLevelSelector_Green"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_BLUE "ChunkBlackLevelSelector_Blue"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_Y "ChunkBlackLevelSelector_Y"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_U "ChunkBlackLevelSelector_U"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_V "ChunkBlackLevelSelector_V"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP1 "ChunkBlackLevelSelector_Tap1"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP2 "ChunkBlackLevelSelector_Tap2"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP3 "ChunkBlackLevelSelector_Tap3"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP4 "ChunkBlackLevelSelector_Tap4"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP5 "ChunkBlackLevelSelector_Tap5"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP6 "ChunkBlackLevelSelector_Tap6"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP7 "ChunkBlackLevelSelector_Tap7"
#define SFNC_CHUNKBLACKLEVELSELECTORVALUE_TAP8 "ChunkBlackLevelSelector_Tap8"
    
#define SFNC_FILESELECTORVALUE_USERSETDEFAULT "FileSelector_UserSetDefault"
#define SFNC_FILESELECTORVALUE_USERSET1 "FileSelector_UserSet1"
#define SFNC_FILESELECTORVALUE_USERSET2 "FileSelector_UserSet2"
#define SFNC_FILESELECTORVALUE_USERSET3 "FileSelector_UserSet3"
#define SFNC_FILESELECTORVALUE_USERSET4 "FileSelector_UserSet4"
#define SFNC_FILESELECTORVALUE_LUTLUMINANCE "FileSelector_LUTLuminance"
#define SFNC_FILESELECTORVALUE_LUTRED "FileSelector_LUTRed"
#define SFNC_FILESELECTORVALUE_LUTGREEN "FileSelector_LUTGreen"
#define SFNC_FILESELECTORVALUE_LUTBLUE "FileSelector_LUTBlue"
   
#define SFNC_FILEOPERATIONSELECTORVALUE_OPEN "FileOperationSelector_Open"
#define SFNC_FILEOPERATIONSELECTORVALUE_CLOSE "FileOperationSelector_Close"
#define SFNC_FILEOPERATIONSELECTORVALUE_READ "FileOperationSelector_Read"
#define SFNC_FILEOPERATIONSELECTORVALUE_WRITE "FileOperationSelector_Write"
#define SFNC_FILEOPERATIONSELECTORVALUE_DELETE "FileOperationSelector_Delete"
    
#define SFNC_COLORTRANSFORMATIONSELECTORVALUE_RGBTORGB "ColorTransformationSelector_RGBtoRGB"
#define SFNC_COLORTRANSFORMATIONSELECTORVALUE_RGBTOYUV "ColorTransformationSelector_RGBtoYUV"

#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain00 "ColorTransformationValueSelector_Gain00"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain01 "ColorTransformationValueSelector_Gain01"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain02 "ColorTransformationValueSelector_Gain02"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain10 "ColorTransformationValueSelector_Gain10"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain11 "ColorTransformationValueSelector_Gain11"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain12 "ColorTransformationValueSelector_Gain12"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain20 "ColorTransformationValueSelector_Gain20"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain21 "ColorTransformationValueSelector_Gain21"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Gain22 "ColorTransformationValueSelector_Gain22"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Offset0 "ColorTransformationValueSelector_Offset0"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Offset1 "ColorTransformationValueSelector_Offset1"
#define SFNC_COLORTRANSFORMATIONVALUESELECTORVALUE_Offset2 "ColorTransformationValueSelector_Offset2"
  
#endif //_BGAPI2_FEATURENAMES_H__
